# <u>Yelp Rating Prediction Using Tensorflow</u>

## **Modeling (relu and adam):**

### *Libraries*

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

#import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
#import sys
#import sklearn as sk
import pandas as pd
import os
#import sklearn.feature_extraction.text as sk_text
#import re

from collections.abc import Sequence
from sklearn import preprocessing
#import shutil
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc  
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense#, Activation
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn import metrics as mt

### *Functions*

In [1]:
# from labs

# Encode text values to dummy variables(i.e. [1,0,0],[0,1,0],[0,0,1] for red,green,blue)
def encode_text_dummy(df, name):
    dummies = pd.get_dummies(df[name])
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name, x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)


# Encode text values to indexes(i.e. [1],[2],[3] for red,green,blue).
def encode_text_index(df, name):
    le = preprocessing.LabelEncoder()
    df[name] = le.fit_transform(df[name])
    return le.classes_


# Encode a numeric column as zscores
def encode_numeric_zscore(df, name, mean=None, sd=None):
    if mean is None:
        mean = df[name].mean()

    if sd is None:
        sd = df[name].std()

    df[name] = (df[name] - mean) / sd


# Convert all missing values in the specified column to the median
def missing_median(df, name):
    med = df[name].median()
    df[name] = df[name].fillna(med)


# Convert all missing values in the specified column to the default
def missing_default(df, name, default_value):
    df[name] = df[name].fillna(default_value)


# Convert a Pandas dataframe to the x,y inputs that TensorFlow needs
def to_xy(df, target):
    result = []
    for x in df.columns:
        if x != target:
            result.append(x)
    # find out the type of the target column.
    target_type = df[target].dtypes
    target_type = target_type[0] if isinstance(target_type, Sequence) else target_type
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    if target_type in (np.int64, np.int32):
        # Classification
        dummies = pd.get_dummies(df[target])
        return df[result].values.astype(np.float32), dummies.values.astype(np.float32)
    else:
        # Regression
        return df[result].values.astype(np.float32), df[target].values.astype(np.float32)

# Nicely formatted time string
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{}:{:>02}:{:>05.2f}".format(h, m, s)


# Regression chart.
def chart_regression(pred,y,sort=True, sample_size=100, figsize=(15,10), title='Lift Chart, Random Sample'):
    t = pd.DataFrame({'pred' : pred, 'y' : y.flatten()})
    if sort:
        t.sort_values(by=['y'],inplace=True)
    if len(t) > sample_size:
        t = t.sample(sample_size, random_state=42)
    plt.figure(figsize=figsize)
    plt.title(title)
    a = plt.plot(t['y'].tolist(),label='expected')
    b = plt.plot(t['pred'].tolist(),label='prediction')
    plt.ylabel('output')
    plt.legend()
    plt.show()
    
# Remove all rows where the specified column is +/- sd standard deviations
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean()) >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)

# Remove all rows where the specified column is +/- sd standard deviations
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean()) >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)


# Encode a column to a range between normalized_low and normalized_high.
def encode_numeric_range(df, name, normalized_low=-1, normalized_high=1,
                         data_low=None, data_high=None):
    if data_low is None:
        data_low = min(df[name])
        data_high = max(df[name])

    df[name] = ((df[name] - data_low) / (data_high - data_low)) \
               * (normalized_high - normalized_low) + normalized_low
    
# Plot an ROC. pred - the predictions, y - the expected output.
def plot_roc(pred,y):
    fpr, tpr, thresholds = roc_curve(y, pred)
    roc_auc = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc)
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic (ROC)')
    plt.legend(loc="lower right")
    plt.show()

### *Load dataframe from file*

In [5]:
df = pd.read_csv("data/df_data.csv")
df.head()

stars  able  absolutely  actually  almost  also  always  amazing   another  \
0      3   0.0         0.0       0.0     0.0   0.0     0.0      0.0  0.168147   
1      2   0.0         0.0       0.0     0.0   0.0     0.0      0.0  0.000000   
2      4   0.0         0.0       0.0     0.0   0.0     0.0      0.0  0.262300   
3      3   0.0         0.0       0.0     0.0   0.0     0.0      0.0  0.128253   
4      2   0.0         0.0       0.0     0.0   0.0     0.0      0.0  0.000000   

   anything  ...  wing  without  wonderful  wont  work     worth     would  \
0  0.000000  ...   0.0      0.0        0.0   0.0   0.0  0.000000  0.000000   
1  0.000000  ...   0.0      0.0        0.0   0.0   0.0  0.000000  0.000000   
2  0.000000  ...   0.0      0.0        0.0   0.0   0.0  0.000000  0.000000   
3  0.000000  ...   0.0      0.0        0.0   0.0   0.0  0.000000  0.090665   
4  0.129936  ...   0.0      0.0        0.0   0.0   0.0  0.118585  0.000000   

      wrong  year  youre  
0  0.000000   0.0    0.0  
1  0.000000   0.0    0.0  
2  0.000000   0.0    0.0  
3  0.000000   0.0    0.0  
4  0.141233   0.0    0.0  

[5 rows x 351 columns]

### *Use dataframe to configure x, y*

In [6]:
x, y = to_xy(df, 'stars')

### *x info*

In [5]:
print('shape:', x.shape)
print(x)

shape: (6146631, 350)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### *y info*

In [6]:
print('shape:', y.shape)
print(y)

shape: (6146631, 5)
[[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]


### *Separate test and train sets*

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

### *Train model*

In [40]:


# create sequential model
model = Sequential()
model.add(Dense(200, input_dim=x.shape[1], activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='mean_squared_error', optimizer='adam')

monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=2, verbose=2, mode='auto')

checkpointer = ModelCheckpoint(filepath="dnn/relu_adam_best_weights.hdf5", verbose=0, save_best_only=True)

model.fit(x_train, y_train, validation_data=(x_test, y_test), callbacks=[monitor, checkpointer], verbose=2, epochs=100)

Epoch 1/100
153666/153666 - 190s - loss: 0.0949 - val_loss: 0.0938 - 190s/epoch - 1ms/step
Epoch 2/100


c:\Users\cdub6\anaconda3\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


153666/153666 - 178s - loss: 0.0932 - val_loss: 0.0934 - 178s/epoch - 1ms/step
Epoch 3/100
153666/153666 - 178s - loss: 0.0927 - val_loss: 0.0936 - 178s/epoch - 1ms/step
Epoch 3: early stopping


### *Load best model*

In [9]:
# skip if you want to see current model results
print('Training finished...Loading the best model')
model.load_weights('dnn/relu_adam_best_weights.hdf5')

Training finished...Loading the best model


### *Optional start point*

In [9]:
# if starting here:  load library, functions, load dataframe, configure x,y, and train/test split cells before running this cell
path = "./dnn/"
model = load_model(os.path.join(path, "relu_adam_best_weights.hdf5"))

### *Model prediction*

In [3]:

prediction = model.predict(x_test)
print("Shape: {}".format(prediction.shape))
print(prediction)

NameError: name 'model' is not defined

## **Results:**

### *Predictions vs. Actual*

In [11]:
predicted_stars = np.argmax(prediction, axis=1)
true_stars = np.argmax(y_test, axis=1)
print("Predictions: {}".format(predicted_stars))
print("Actual: {}".format(true_stars))

Predictions: [4 3 0 ... 2 4 4]
Actual: [4 2 0 ... 0 4 0]


### *Accuracy*

In [12]:
accuracy = mt.accuracy_score(true_stars, predicted_stars)
print("Accuracy score: {}".format(accuracy))

Accuracy score: 0.642445012596323


### *Precision*

In [13]:
precision = mt.precision_score(true_stars, predicted_stars, average="weighted")
print("Precision score: {}".format(precision))


Precision score: 0.6120219180404946


### *Recall score*

In [14]:
recall = mt.recall_score(true_stars, predicted_stars, average="weighted")
print("Recall score: {}".format(recall))

Recall score: 0.642445012596323


### *F1 score*

In [15]:
f1 = mt.f1_score(true_stars, predicted_stars, average="weighted")
print("F1 score: {}".format(f1))

F1 score: 0.6183841402317621


### *Log score*

In [16]:
log_score = mt.log_loss(y_test, prediction)
print("Log loss score: {}".format(log_score))

Log loss score: 0.8648697944915801


### *Classification report*

In [17]:
print(mt.classification_report(true_stars, predicted_stars))

              precision    recall  f1-score   support

           0       0.67      0.78      0.72    172632
           1       0.40      0.24      0.30     98018
           2       0.43      0.32      0.37    127331
           3       0.50      0.36      0.42    268156
           4       0.73      0.88      0.79    563190

    accuracy                           0.64   1229327
   macro avg       0.55      0.52      0.52   1229327
weighted avg       0.61      0.64      0.62   1229327



### *Mean Squared Error (MSE)*

In [18]:
mse = mt.mean_squared_error(prediction, y_test)
print('Final score (MSE): {}'.format(mse))


Final score (MSE): 0.09324964135885239


### *Root Mean Squared Error (RMSE)*

In [19]:
score = np.sqrt(mt.mean_squared_error(prediction, y_test))
print('Final score (RMSE): {}'.format(score))

Final score (RMSE): 0.305368036031723


### *Actual vs. predicted*

In [20]:
df_y = pd.DataFrame(true_stars, columns=['actual'])
df_pred = pd.DataFrame(predicted_stars, columns=['predicted'])
result = pd.concat([df_y, df_pred], axis=1)
result

actual  predicted
0             4          4
1             2          3
2             0          0
3             3          4
4             2          3
...         ...        ...
1229322       3          3
1229323       3          4
1229324       0          2
1229325       4          4
1229326       0          4

[1229327 rows x 2 columns]

### *Regression lift chart*

In [2]:
chart_regression(prediction.flatten(), y_test, sort=True)

NameError: name 'prediction' is not defined